# HAT (Hub of All Things) Configuration
# Configuration for Dataswift HAT integration and personal data vaults

hat:
  # HAT Service Configuration
  service:
    application_id: "idaho-shelter-management"
    namespace: "shelter"
    kind: "shelter-management-app"
    api_version: "v2.6"
    secure: true
    domain: "hubofallthings.net"
    
  # Authentication
  auth:
    client_id: "${HAT_CLIENT_ID}"
    client_secret: "${HAT_CLIENT_SECRET}"
    redirect_uri: "${HAT_REDIRECT_URI:-http://localhost:3000/hat/callback}"
    
  # Data Schemas
  schemas:
    client_profile:
      namespace: "shelter"
      name: "client_profile"
      version: "1.0.0"
      fields:
        - name: "firstName"
          type: "string"
          required: true
        - name: "lastName" 
          type: "string"
          required: true
        - name: "dateOfBirth"
          type: "date"
          required: false
        - name: "phone"
          type: "string"
          required: false
        - name: "email"
          type: "string"
          required: false
          
    health_data:
      namespace: "shelter"
      name: "health_data"
      version: "1.0.0"
      fields:
        - name: "bloodPressure"
          type: "object"
          properties:
            systolic: "number"
            diastolic: "number"
            timestamp: "datetime"
        - name: "medications"
          type: "array"
          items:
            type: "object"
            properties:
              name: "string"
              dosage: "string"
              frequency: "string"
              
    stay_history:
      namespace: "shelter"
      name: "stay_history"
      version: "1.0.0"
      fields:
        - name: "checkInDate"
          type: "datetime"
          required: true
        - name: "checkOutDate"
          type: "datetime"
          required: false
        - name: "bedNumber"
          type: "string"
          required: true
        - name: "notes"
          type: "string"
          required: false
          
  # Privacy Configuration
  privacy:
    encryption:
      enabled: true
      algorithm: "AES-256-GCM"
    data_retention:
      default_days: 2555  # 7 years
      medical_data_days: 3650  # 10 years
      can_be_deleted: true
      
  # API Endpoints
  endpoints:
    base_url: "https://api.hubofallthings.com"
    auth: "/auth"
    data: "/data"
    applications: "/applications"
    
development:
  # Development settings
  base_url: "https://sandbox-api.hubofallthings.com"
  debug_logging: true
  
production:
  # Production settings
  base_url: "https://api.hubofallthings.com"
  debug_logging: false
